before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64-build
    main: ./cmd/rarimo-cored
    binary: rarimo-core
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64