// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rarimocore/deposit.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_NATIVE       Type = 0
	Type_ERC20        Type = 1
	Type_ERC721       Type = 2
	Type_ERC1155      Type = 3
	Type_METAPLEX_NFT Type = 4
	Type_METAPLEX_FT  Type = 5
)

var Type_name = map[int32]string{
	0: "NATIVE",
	1: "ERC20",
	2: "ERC721",
	3: "ERC1155",
	4: "METAPLEX_NFT",
	5: "METAPLEX_FT",
}

var Type_value = map[string]int32{
	"NATIVE":       0,
	"ERC20":        1,
	"ERC721":       2,
	"ERC1155":      3,
	"METAPLEX_NFT": 4,
	"METAPLEX_FT":  5,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_24f8a86eafda8811, []int{0}
}

type Deposit struct {
	Tx        string `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	EventId   string `protobuf:"bytes,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	FromChain string `protobuf:"bytes,3,opt,name=fromChain,proto3" json:"fromChain,omitempty"`
	ToChain   string `protobuf:"bytes,4,opt,name=toChain,proto3" json:"toChain,omitempty"`
	// hex-encoded
	Receiver string `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// hex-encoded
	TokenAddress string `protobuf:"bytes,6,opt,name=tokenAddress,proto3" json:"tokenAddress,omitempty"`
	// hex-encoded
	TokenId   string `protobuf:"bytes,7,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	Creator   string `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	Signed    bool   `protobuf:"varint,9,opt,name=signed,proto3" json:"signed,omitempty"`
	TokenType Type   `protobuf:"varint,10,opt,name=tokenType,proto3,enum=rarifyprotocol.rarimocore.rarimocore.Type" json:"tokenType,omitempty"`
}

func (m *Deposit) Reset()         { *m = Deposit{} }
func (m *Deposit) String() string { return proto.CompactTextString(m) }
func (*Deposit) ProtoMessage()    {}
func (*Deposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f8a86eafda8811, []int{0}
}
func (m *Deposit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Deposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Deposit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Deposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deposit.Merge(m, src)
}
func (m *Deposit) XXX_Size() int {
	return m.Size()
}
func (m *Deposit) XXX_DiscardUnknown() {
	xxx_messageInfo_Deposit.DiscardUnknown(m)
}

var xxx_messageInfo_Deposit proto.InternalMessageInfo

func (m *Deposit) GetTx() string {
	if m != nil {
		return m.Tx
	}
	return ""
}

func (m *Deposit) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *Deposit) GetFromChain() string {
	if m != nil {
		return m.FromChain
	}
	return ""
}

func (m *Deposit) GetToChain() string {
	if m != nil {
		return m.ToChain
	}
	return ""
}

func (m *Deposit) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Deposit) GetTokenAddress() string {
	if m != nil {
		return m.TokenAddress
	}
	return ""
}

func (m *Deposit) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *Deposit) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Deposit) GetSigned() bool {
	if m != nil {
		return m.Signed
	}
	return false
}

func (m *Deposit) GetTokenType() Type {
	if m != nil {
		return m.TokenType
	}
	return Type_NATIVE
}

func init() {
	proto.RegisterEnum("rarifyprotocol.rarimocore.rarimocore.Type", Type_name, Type_value)
	proto.RegisterType((*Deposit)(nil), "rarifyprotocol.rarimocore.rarimocore.Deposit")
}

func init() { proto.RegisterFile("rarimocore/deposit.proto", fileDescriptor_24f8a86eafda8811) }

var fileDescriptor_24f8a86eafda8811 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0xca, 0xda, 0x40,
	0x14, 0xc5, 0x33, 0x51, 0x13, 0x73, 0x15, 0x1b, 0x66, 0x51, 0x86, 0x52, 0x82, 0x48, 0x17, 0x22,
	0x98, 0x54, 0x8b, 0x94, 0x2e, 0x6d, 0x1a, 0xa9, 0xd0, 0x4a, 0x49, 0x43, 0x69, 0xbb, 0x29, 0x31,
	0x19, 0x6d, 0x50, 0x33, 0x61, 0x32, 0x88, 0xbe, 0x45, 0x5f, 0xa9, 0xbb, 0x2e, 0x5d, 0x76, 0x59,
	0xf4, 0x45, 0x4a, 0x26, 0xfe, 0xfb, 0x76, 0xdf, 0x6e, 0xce, 0xf9, 0xdd, 0x73, 0x39, 0x0c, 0x17,
	0x08, 0x0f, 0x79, 0xb2, 0x61, 0x11, 0xe3, 0xd4, 0x89, 0x69, 0xc6, 0xf2, 0x44, 0xd8, 0x19, 0x67,
	0x82, 0xe1, 0x17, 0x05, 0x59, 0xec, 0xa5, 0x88, 0xd8, 0xda, 0xbe, 0x0d, 0xde, 0x3d, 0x3b, 0xbf,
	0x55, 0xd0, 0xdf, 0x95, 0x39, 0xdc, 0x02, 0x55, 0xec, 0x08, 0x6a, 0xa3, 0xae, 0xe1, 0xab, 0x62,
	0x87, 0x09, 0xe8, 0x74, 0x4b, 0x53, 0x31, 0x8d, 0x89, 0x2a, 0xcd, 0x8b, 0xc4, 0xcf, 0xc1, 0x58,
	0x70, 0xb6, 0x71, 0x7f, 0x86, 0x49, 0x4a, 0x2a, 0x92, 0xdd, 0x8c, 0x22, 0x27, 0x58, 0xc9, 0xaa,
	0x65, 0xee, 0x2c, 0xf1, 0x33, 0xa8, 0x73, 0x1a, 0xd1, 0x64, 0x4b, 0x39, 0xa9, 0x49, 0x74, 0xd5,
	0xb8, 0x03, 0x4d, 0xc1, 0x56, 0x34, 0x1d, 0xc7, 0x31, 0xa7, 0x79, 0x4e, 0x34, 0xc9, 0x1f, 0x78,
	0xe5, 0xe6, 0x15, 0x4d, 0xa7, 0x31, 0xd1, 0x2f, 0x9b, 0xa5, 0x2c, 0x48, 0xc4, 0x69, 0x28, 0x18,
	0x27, 0xf5, 0x92, 0x9c, 0x25, 0x7e, 0x0a, 0x5a, 0x9e, 0x2c, 0x53, 0x1a, 0x13, 0xa3, 0x8d, 0xba,
	0x75, 0xff, 0xac, 0xf0, 0x7b, 0x30, 0x64, 0x38, 0xd8, 0x67, 0x94, 0x40, 0x1b, 0x75, 0x5b, 0xc3,
	0x9e, 0xfd, 0x98, 0x3f, 0xb3, 0xc5, 0x3e, 0xa3, 0xfe, 0x2d, 0xdc, 0xfb, 0x06, 0xd5, 0xc2, 0xc2,
	0x00, 0xda, 0x6c, 0x1c, 0x4c, 0xbf, 0x78, 0xa6, 0x82, 0x0d, 0xa8, 0x79, 0xbe, 0x3b, 0x7c, 0x69,
	0xa2, 0xc2, 0xf6, 0x7c, 0xf7, 0xf5, 0x70, 0x60, 0xaa, 0xb8, 0x01, 0xba, 0xe7, 0xbb, 0x83, 0xc1,
	0x68, 0x64, 0x56, 0xb0, 0x09, 0xcd, 0x8f, 0x5e, 0x30, 0xfe, 0xf4, 0xc1, 0xfb, 0xfa, 0x63, 0x36,
	0x09, 0xcc, 0x2a, 0x7e, 0x02, 0x8d, 0xab, 0x33, 0x09, 0xcc, 0xda, 0xdb, 0xcf, 0x7f, 0x8e, 0x16,
	0x3a, 0x1c, 0x2d, 0xf4, 0xef, 0x68, 0xa1, 0x5f, 0x27, 0x4b, 0x39, 0x9c, 0x2c, 0xe5, 0xef, 0xc9,
	0x52, 0xbe, 0xbf, 0x59, 0x26, 0x62, 0x1d, 0xce, 0xed, 0x88, 0x6d, 0x9c, 0xb2, 0x75, 0xff, 0x52,
	0xdb, 0x29, 0xbb, 0xf6, 0xe5, 0x51, 0xec, 0x9c, 0xbb, 0x0b, 0x29, 0x6a, 0xe6, 0x73, 0x4d, 0x0e,
	0xbe, 0xfa, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xb7, 0x51, 0x43, 0x3c, 0x02, 0x00, 0x00,
}

func (m *Deposit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Deposit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Deposit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TokenType != 0 {
		i = encodeVarintDeposit(dAtA, i, uint64(m.TokenType))
		i--
		dAtA[i] = 0x50
	}
	if m.Signed {
		i--
		if m.Signed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.TokenId) > 0 {
		i -= len(m.TokenId)
		copy(dAtA[i:], m.TokenId)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.TokenId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.TokenAddress) > 0 {
		i -= len(m.TokenAddress)
		copy(dAtA[i:], m.TokenAddress)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.TokenAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ToChain) > 0 {
		i -= len(m.ToChain)
		copy(dAtA[i:], m.ToChain)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.ToChain)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.FromChain) > 0 {
		i -= len(m.FromChain)
		copy(dAtA[i:], m.FromChain)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.FromChain)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.EventId) > 0 {
		i -= len(m.EventId)
		copy(dAtA[i:], m.EventId)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.EventId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tx) > 0 {
		i -= len(m.Tx)
		copy(dAtA[i:], m.Tx)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.Tx)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDeposit(dAtA []byte, offset int, v uint64) int {
	offset -= sovDeposit(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Deposit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Tx)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	l = len(m.EventId)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	l = len(m.FromChain)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	l = len(m.ToChain)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	l = len(m.TokenAddress)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	l = len(m.TokenId)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	if m.Signed {
		n += 2
	}
	if m.TokenType != 0 {
		n += 1 + sovDeposit(uint64(m.TokenType))
	}
	return n
}

func sovDeposit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDeposit(x uint64) (n int) {
	return sovDeposit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Deposit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeposit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Deposit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Deposit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tx = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Signed = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenType", wireType)
			}
			m.TokenType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenType |= Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDeposit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeposit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDeposit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDeposit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDeposit
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDeposit
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDeposit
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDeposit        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDeposit          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDeposit = fmt.Errorf("proto: unexpected end of group")
)
