// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rarimocore/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	types "gitlab.com/rarify-protocol/rarimo-core/x/tokenmanager/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateTransferOp struct {
	Creator   string     `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Tx        string     `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	EventId   string     `protobuf:"bytes,3,opt,name=eventId,proto3" json:"eventId,omitempty"`
	FromChain string     `protobuf:"bytes,4,opt,name=fromChain,proto3" json:"fromChain,omitempty"`
	TokenType types.Type `protobuf:"varint,5,opt,name=tokenType,proto3,enum=rarifyprotocol.rarimocore.tokenmanager.Type" json:"tokenType,omitempty"`
}

func (m *MsgCreateTransferOp) Reset()         { *m = MsgCreateTransferOp{} }
func (m *MsgCreateTransferOp) String() string { return proto.CompactTextString(m) }
func (*MsgCreateTransferOp) ProtoMessage()    {}
func (*MsgCreateTransferOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9dffb74ddf0d475, []int{0}
}
func (m *MsgCreateTransferOp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateTransferOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateTransferOp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateTransferOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateTransferOp.Merge(m, src)
}
func (m *MsgCreateTransferOp) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateTransferOp) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateTransferOp.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateTransferOp proto.InternalMessageInfo

func (m *MsgCreateTransferOp) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateTransferOp) GetTx() string {
	if m != nil {
		return m.Tx
	}
	return ""
}

func (m *MsgCreateTransferOp) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *MsgCreateTransferOp) GetFromChain() string {
	if m != nil {
		return m.FromChain
	}
	return ""
}

func (m *MsgCreateTransferOp) GetTokenType() types.Type {
	if m != nil {
		return m.TokenType
	}
	return types.Type_NATIVE
}

type MsgCreateTransferOpResponse struct {
}

func (m *MsgCreateTransferOpResponse) Reset()         { *m = MsgCreateTransferOpResponse{} }
func (m *MsgCreateTransferOpResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateTransferOpResponse) ProtoMessage()    {}
func (*MsgCreateTransferOpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9dffb74ddf0d475, []int{1}
}
func (m *MsgCreateTransferOpResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateTransferOpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateTransferOpResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateTransferOpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateTransferOpResponse.Merge(m, src)
}
func (m *MsgCreateTransferOpResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateTransferOpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateTransferOpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateTransferOpResponse proto.InternalMessageInfo

type MsgCreateConfirmation struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// hex-encoded
	Root    string   `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Indexes []string `protobuf:"bytes,3,rep,name=indexes,proto3" json:"indexes,omitempty"`
	// hex-encoded
	SignatureECDSA string `protobuf:"bytes,4,opt,name=signatureECDSA,proto3" json:"signatureECDSA,omitempty"`
}

func (m *MsgCreateConfirmation) Reset()         { *m = MsgCreateConfirmation{} }
func (m *MsgCreateConfirmation) String() string { return proto.CompactTextString(m) }
func (*MsgCreateConfirmation) ProtoMessage()    {}
func (*MsgCreateConfirmation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9dffb74ddf0d475, []int{2}
}
func (m *MsgCreateConfirmation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateConfirmation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateConfirmation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateConfirmation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateConfirmation.Merge(m, src)
}
func (m *MsgCreateConfirmation) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateConfirmation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateConfirmation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateConfirmation proto.InternalMessageInfo

func (m *MsgCreateConfirmation) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateConfirmation) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *MsgCreateConfirmation) GetIndexes() []string {
	if m != nil {
		return m.Indexes
	}
	return nil
}

func (m *MsgCreateConfirmation) GetSignatureECDSA() string {
	if m != nil {
		return m.SignatureECDSA
	}
	return ""
}

type MsgCreateConfirmationResponse struct {
}

func (m *MsgCreateConfirmationResponse) Reset()         { *m = MsgCreateConfirmationResponse{} }
func (m *MsgCreateConfirmationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateConfirmationResponse) ProtoMessage()    {}
func (*MsgCreateConfirmationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9dffb74ddf0d475, []int{3}
}
func (m *MsgCreateConfirmationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateConfirmationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateConfirmationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateConfirmationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateConfirmationResponse.Merge(m, src)
}
func (m *MsgCreateConfirmationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateConfirmationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateConfirmationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateConfirmationResponse proto.InternalMessageInfo

type MsgCreateChangeKeyECDSA struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// hex-encoded
	NewKey string `protobuf:"bytes,2,opt,name=newKey,proto3" json:"newKey,omitempty"`
}

func (m *MsgCreateChangeKeyECDSA) Reset()         { *m = MsgCreateChangeKeyECDSA{} }
func (m *MsgCreateChangeKeyECDSA) String() string { return proto.CompactTextString(m) }
func (*MsgCreateChangeKeyECDSA) ProtoMessage()    {}
func (*MsgCreateChangeKeyECDSA) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9dffb74ddf0d475, []int{4}
}
func (m *MsgCreateChangeKeyECDSA) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateChangeKeyECDSA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateChangeKeyECDSA.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateChangeKeyECDSA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateChangeKeyECDSA.Merge(m, src)
}
func (m *MsgCreateChangeKeyECDSA) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateChangeKeyECDSA) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateChangeKeyECDSA.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateChangeKeyECDSA proto.InternalMessageInfo

func (m *MsgCreateChangeKeyECDSA) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateChangeKeyECDSA) GetNewKey() string {
	if m != nil {
		return m.NewKey
	}
	return ""
}

type MsgCreateChangeKeyECDSAResponse struct {
}

func (m *MsgCreateChangeKeyECDSAResponse) Reset()         { *m = MsgCreateChangeKeyECDSAResponse{} }
func (m *MsgCreateChangeKeyECDSAResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateChangeKeyECDSAResponse) ProtoMessage()    {}
func (*MsgCreateChangeKeyECDSAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9dffb74ddf0d475, []int{5}
}
func (m *MsgCreateChangeKeyECDSAResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateChangeKeyECDSAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateChangeKeyECDSAResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateChangeKeyECDSAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateChangeKeyECDSAResponse.Merge(m, src)
}
func (m *MsgCreateChangeKeyECDSAResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateChangeKeyECDSAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateChangeKeyECDSAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateChangeKeyECDSAResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateTransferOp)(nil), "rarifyprotocol.rarimocore.rarimocore.MsgCreateTransferOp")
	proto.RegisterType((*MsgCreateTransferOpResponse)(nil), "rarifyprotocol.rarimocore.rarimocore.MsgCreateTransferOpResponse")
	proto.RegisterType((*MsgCreateConfirmation)(nil), "rarifyprotocol.rarimocore.rarimocore.MsgCreateConfirmation")
	proto.RegisterType((*MsgCreateConfirmationResponse)(nil), "rarifyprotocol.rarimocore.rarimocore.MsgCreateConfirmationResponse")
	proto.RegisterType((*MsgCreateChangeKeyECDSA)(nil), "rarifyprotocol.rarimocore.rarimocore.MsgCreateChangeKeyECDSA")
	proto.RegisterType((*MsgCreateChangeKeyECDSAResponse)(nil), "rarifyprotocol.rarimocore.rarimocore.MsgCreateChangeKeyECDSAResponse")
}

func init() { proto.RegisterFile("rarimocore/tx.proto", fileDescriptor_d9dffb74ddf0d475) }

var fileDescriptor_d9dffb74ddf0d475 = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x3d, 0x6f, 0xd4, 0x40,
	0x10, 0xbd, 0x3d, 0x87, 0xa0, 0x9b, 0xe2, 0x8a, 0x0d, 0x70, 0x96, 0xe1, 0x9c, 0xc3, 0x42, 0x28,
	0x05, 0xb1, 0xa5, 0x50, 0x45, 0x88, 0x22, 0x98, 0x14, 0x70, 0x8a, 0x90, 0x2e, 0xa9, 0xe8, 0x36,
	0xce, 0x9c, 0x63, 0x11, 0xef, 0x5a, 0xeb, 0x05, 0xec, 0x5f, 0x40, 0x4b, 0x05, 0x0d, 0xff, 0x86,
	0x86, 0x32, 0x1d, 0x94, 0xe8, 0xee, 0x8f, 0x20, 0x7f, 0x9d, 0x97, 0xc8, 0x89, 0x08, 0xe9, 0x76,
	0x66, 0xde, 0x9b, 0x79, 0x6f, 0x67, 0xb5, 0xb0, 0x21, 0x99, 0x8c, 0x62, 0x11, 0x08, 0x89, 0x9e,
	0xca, 0xdc, 0x44, 0x0a, 0x25, 0xe8, 0xa3, 0x22, 0x39, 0xcf, 0xcb, 0x20, 0x10, 0x67, 0x6e, 0x8b,
	0xd1, 0x8e, 0x96, 0xa5, 0x51, 0x45, 0x82, 0x92, 0xa9, 0x48, 0xf0, 0xaa, 0x83, 0x35, 0xd6, 0x6a,
	0x81, 0xe0, 0xf3, 0x48, 0xc6, 0x7a, 0x79, 0xa4, 0xc4, 0x3b, 0xe4, 0x31, 0xe3, 0x2c, 0x44, 0xe9,
	0x45, 0x0a, 0xe3, 0xaa, 0xe0, 0x7c, 0x27, 0xb0, 0x71, 0x90, 0x86, 0xbe, 0x44, 0xa6, 0xf0, 0x48,
	0x32, 0x9e, 0xce, 0x51, 0xbe, 0x49, 0xa8, 0x09, 0xb7, 0x83, 0x22, 0x27, 0xa4, 0x49, 0x26, 0x64,
	0x6b, 0x30, 0x6b, 0x42, 0x3a, 0x84, 0xbe, 0xca, 0xcc, 0x7e, 0x99, 0xec, 0xab, 0xac, 0x40, 0xe2,
	0x07, 0xe4, 0xea, 0xd5, 0x89, 0x69, 0x54, 0xc8, 0x3a, 0xa4, 0x0f, 0x60, 0x30, 0x97, 0x22, 0xf6,
	0x4f, 0x59, 0xc4, 0xcd, 0xb5, 0xb2, 0xd6, 0x26, 0xe8, 0x6b, 0x18, 0x94, 0xa2, 0x8e, 0xf2, 0x04,
	0xcd, 0x5b, 0x13, 0xb2, 0x35, 0xdc, 0x79, 0xe2, 0x5e, 0x7e, 0x0f, 0xba, 0x01, 0x57, 0xe5, 0x09,
	0xce, 0x5a, 0xba, 0x33, 0x86, 0xfb, 0x1d, 0x26, 0x66, 0x98, 0x26, 0x82, 0xa7, 0xe8, 0x7c, 0x22,
	0x70, 0x77, 0x55, 0xf7, 0xb5, 0xdb, 0xb9, 0xc2, 0x26, 0x85, 0x35, 0x29, 0x84, 0xaa, 0x8d, 0x96,
	0xe7, 0x02, 0x1d, 0xf1, 0x13, 0xcc, 0x30, 0x35, 0x8d, 0x89, 0x51, 0xa0, 0xeb, 0x90, 0x3e, 0x86,
	0x61, 0x1a, 0x85, 0x9c, 0xa9, 0xf7, 0x12, 0xf7, 0xfd, 0x97, 0x87, 0x7b, 0xb5, 0xdf, 0x0b, 0x59,
	0x67, 0x13, 0xc6, 0x9d, 0x42, 0x56, 0x52, 0xa7, 0x30, 0x6a, 0x01, 0xa7, 0x8c, 0x87, 0x38, 0xc5,
	0xbc, 0xe4, 0x5e, 0xa1, 0xf5, 0x1e, 0xac, 0x73, 0xfc, 0x38, 0xc5, 0xbc, 0x56, 0x5b, 0x47, 0xce,
	0x43, 0xd8, 0xbc, 0xa4, 0x59, 0x33, 0x6f, 0xe7, 0xa7, 0x01, 0xc6, 0x41, 0x1a, 0xd2, 0xaf, 0x04,
	0x46, 0x17, 0xef, 0xaf, 0x7e, 0x61, 0x74, 0xd7, 0xfd, 0x97, 0xe7, 0xe9, 0x76, 0x6c, 0xc0, 0xda,
	0xfb, 0x6f, 0x6a, 0xa3, 0x90, 0x7e, 0x21, 0x40, 0x3b, 0x36, 0xf7, 0xec, 0x9a, 0x9d, 0x75, 0xb2,
	0xe5, 0xdf, 0x80, 0xbc, 0x12, 0xf6, 0x8d, 0xc0, 0x9d, 0xce, 0x45, 0x3d, 0xbf, 0x6e, 0xf7, 0xbf,
	0xe8, 0xd6, 0xfe, 0x8d, 0xe8, 0x8d, 0xbc, 0x17, 0x87, 0x3f, 0x16, 0x36, 0x39, 0x5f, 0xd8, 0xe4,
	0xf7, 0xc2, 0x26, 0x9f, 0x97, 0x76, 0xef, 0x7c, 0x69, 0xf7, 0x7e, 0x2d, 0xed, 0xde, 0xdb, 0xdd,
	0x30, 0x52, 0x67, 0xec, 0xd8, 0x0d, 0x44, 0xec, 0x55, 0xa3, 0xb6, 0x9b, 0x59, 0x5e, 0x35, 0x60,
	0xbb, 0xfc, 0x47, 0x32, 0x4f, 0xff, 0xab, 0xf2, 0x04, 0xd3, 0xe3, 0xf5, 0x12, 0xf8, 0xf4, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x2e, 0x68, 0x82, 0xc6, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateTransferOperation(ctx context.Context, in *MsgCreateTransferOp, opts ...grpc.CallOption) (*MsgCreateTransferOpResponse, error)
	CreateConfirmation(ctx context.Context, in *MsgCreateConfirmation, opts ...grpc.CallOption) (*MsgCreateConfirmationResponse, error)
	CreateChangeKeyECDSA(ctx context.Context, in *MsgCreateChangeKeyECDSA, opts ...grpc.CallOption) (*MsgCreateChangeKeyECDSAResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateTransferOperation(ctx context.Context, in *MsgCreateTransferOp, opts ...grpc.CallOption) (*MsgCreateTransferOpResponse, error) {
	out := new(MsgCreateTransferOpResponse)
	err := c.cc.Invoke(ctx, "/rarifyprotocol.rarimocore.rarimocore.Msg/CreateTransferOperation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateConfirmation(ctx context.Context, in *MsgCreateConfirmation, opts ...grpc.CallOption) (*MsgCreateConfirmationResponse, error) {
	out := new(MsgCreateConfirmationResponse)
	err := c.cc.Invoke(ctx, "/rarifyprotocol.rarimocore.rarimocore.Msg/CreateConfirmation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateChangeKeyECDSA(ctx context.Context, in *MsgCreateChangeKeyECDSA, opts ...grpc.CallOption) (*MsgCreateChangeKeyECDSAResponse, error) {
	out := new(MsgCreateChangeKeyECDSAResponse)
	err := c.cc.Invoke(ctx, "/rarifyprotocol.rarimocore.rarimocore.Msg/CreateChangeKeyECDSA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateTransferOperation(context.Context, *MsgCreateTransferOp) (*MsgCreateTransferOpResponse, error)
	CreateConfirmation(context.Context, *MsgCreateConfirmation) (*MsgCreateConfirmationResponse, error)
	CreateChangeKeyECDSA(context.Context, *MsgCreateChangeKeyECDSA) (*MsgCreateChangeKeyECDSAResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateTransferOperation(ctx context.Context, req *MsgCreateTransferOp) (*MsgCreateTransferOpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransferOperation not implemented")
}
func (*UnimplementedMsgServer) CreateConfirmation(ctx context.Context, req *MsgCreateConfirmation) (*MsgCreateConfirmationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConfirmation not implemented")
}
func (*UnimplementedMsgServer) CreateChangeKeyECDSA(ctx context.Context, req *MsgCreateChangeKeyECDSA) (*MsgCreateChangeKeyECDSAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChangeKeyECDSA not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateTransferOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateTransferOp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateTransferOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rarifyprotocol.rarimocore.rarimocore.Msg/CreateTransferOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateTransferOperation(ctx, req.(*MsgCreateTransferOp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateConfirmation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rarifyprotocol.rarimocore.rarimocore.Msg/CreateConfirmation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateConfirmation(ctx, req.(*MsgCreateConfirmation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateChangeKeyECDSA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateChangeKeyECDSA)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateChangeKeyECDSA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rarifyprotocol.rarimocore.rarimocore.Msg/CreateChangeKeyECDSA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateChangeKeyECDSA(ctx, req.(*MsgCreateChangeKeyECDSA))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rarifyprotocol.rarimocore.rarimocore.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTransferOperation",
			Handler:    _Msg_CreateTransferOperation_Handler,
		},
		{
			MethodName: "CreateConfirmation",
			Handler:    _Msg_CreateConfirmation_Handler,
		},
		{
			MethodName: "CreateChangeKeyECDSA",
			Handler:    _Msg_CreateChangeKeyECDSA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rarimocore/tx.proto",
}

func (m *MsgCreateTransferOp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateTransferOp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateTransferOp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TokenType != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TokenType))
		i--
		dAtA[i] = 0x28
	}
	if len(m.FromChain) > 0 {
		i -= len(m.FromChain)
		copy(dAtA[i:], m.FromChain)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromChain)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.EventId) > 0 {
		i -= len(m.EventId)
		copy(dAtA[i:], m.EventId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EventId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Tx) > 0 {
		i -= len(m.Tx)
		copy(dAtA[i:], m.Tx)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tx)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateTransferOpResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateTransferOpResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateTransferOpResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateConfirmation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateConfirmation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateConfirmation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignatureECDSA) > 0 {
		i -= len(m.SignatureECDSA)
		copy(dAtA[i:], m.SignatureECDSA)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignatureECDSA)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Indexes) > 0 {
		for iNdEx := len(m.Indexes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Indexes[iNdEx])
			copy(dAtA[i:], m.Indexes[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Indexes[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateConfirmationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateConfirmationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateConfirmationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateChangeKeyECDSA) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateChangeKeyECDSA) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateChangeKeyECDSA) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewKey) > 0 {
		i -= len(m.NewKey)
		copy(dAtA[i:], m.NewKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateChangeKeyECDSAResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateChangeKeyECDSAResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateChangeKeyECDSAResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateTransferOp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Tx)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EventId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FromChain)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TokenType != 0 {
		n += 1 + sovTx(uint64(m.TokenType))
	}
	return n
}

func (m *MsgCreateTransferOpResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateConfirmation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Indexes) > 0 {
		for _, s := range m.Indexes {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.SignatureECDSA)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateConfirmationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateChangeKeyECDSA) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateChangeKeyECDSAResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateTransferOp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateTransferOp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateTransferOp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tx = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenType", wireType)
			}
			m.TokenType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenType |= types.Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateTransferOpResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateTransferOpResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateTransferOpResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateConfirmation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateConfirmation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateConfirmation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Indexes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Indexes = append(m.Indexes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignatureECDSA", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignatureECDSA = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateConfirmationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateConfirmationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateConfirmationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateChangeKeyECDSA) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateChangeKeyECDSA: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateChangeKeyECDSA: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateChangeKeyECDSAResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateChangeKeyECDSAResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateChangeKeyECDSAResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
