name: Build Rarimo Core executables
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: endsWith(github.event.base_ref, 'mainnet') == false
        run: |
          echo ${{ github.event.base_ref }}
          echo ${{github.ref}}
          exit -1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: GCC multilib
        run: |
          sudo apt-get install gcc-multilib g++-multilib

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          workdir: ./cmd/rarimo-cored
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}